homePage first view
DamianTobiasz/tasks pull request #2
Opened 2022-03-25 17:44 UTC by DamianTobiasz

Problems with ng serve

2022-03-26 20:52 UTC, gradzio requested changes

2022-03-26 20:52 UTC, gradzio commented on projects/home/src/lib/adapters/primary/ui/today.component.html
> +  <p class="px-3 fs-5 d-inline align-middle text-uppercase">Fri 18 MAR</p>
Please use date object to always show todays date

2022-03-28 09:46 UTC, DamianTobiasz commented
Updated view

2022-03-28 19:15 UTC, gradzio requested changes

2022-03-28 19:15 UTC, gradzio commented on projects/home/src/lib/adapters/primary/ui/images-inline.component.ts
> +  images$: Observable<ImageDTO[]> = of([
It should be in the service and fetched via port

2022-03-28 19:15 UTC, gradzio commented on projects/home/src/lib/adapters/primary/ui/today.component.ts
> +  today: Date = new Date();
It should be dto

2022-03-28 19:15 UTC, gradzio commented on src/assets/customStyles.scss
> +.violet {
Please customize bootstrap colors

2022-03-28 19:15 UTC, gradzio commented on src/assets/customStyles.scss
> +  width: 349px;
Use responsivr classes

2022-03-28 19:15 UTC, merged